version: '3.8'
services:
  primary:
    image: postgres:16
    container_name: pg-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./primary/data:/var/lib/postgresql/data
      - ./primary/init-replication.sh:/docker-entrypoint-initdb.d/init-replication.sh:ro
    ports:
      - "5432:5432"

  replica:
    image: postgres:16
    container_name: pg-replica
    depends_on:
      - primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REPLICATOR_PASSWORD: replicator_password
    volumes:
      - ./replica/data:/var/lib/postgresql/data
      - ./replica/replica-entrypoint.sh:/usr/local/bin/replica-entrypoint.sh:ro
    entrypoint: ["/usr/local/bin/replica-entrypoint.sh"]
    ports:
      - "5433:5432"
